# Generated by Django 3.2.5 on 2021-07-27 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='N/A')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default='', editable=False, max_length=100)),
                ('state', models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Deleted', 'Deleted')], default='Pending', max_length=20)),
            ],
        ),
    ]
