# Generated by Django 3.2.5 on 2021-07-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCode',
            new_name='Promo',
        ),
    ]
