# Generated by Django 3.2.5 on 2021-07-27 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0002_rename_qrcode_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='N/A')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='promo',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qrmaker.maker'),
        ),
    ]
