# Generated by Django 3.2.5 on 2021-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0004_maker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
