# Generated by Django 3.2.5 on 2021-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0005_alter_maker_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='title',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='maker',
            name='username',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
