# Generated by Django 3.2.5 on 2021-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0009_auto_20210727_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
