# Generated by Django 3.2.5 on 2021-07-27 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0010_transaction_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='promo',
        ),
        migrations.CreateModel(
            name='PromoInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', max_length=200)),
                ('description', models.TextField(default='N/A')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default='', editable=False, max_length=100)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinstances', to='qrmaker.promo')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='pinstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='qrmaker.promoinstance'),
        ),
    ]
