# Generated by Django 3.2.5 on 2021-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0011_auto_20210727_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='suid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
