# Generated by Django 3.2.5 on 2021-07-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0012_promo_suid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='suid',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
