# Generated by Django 3.2.6 on 2021-08-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmaker', '0014_maker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='target',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='promo',
            name='state',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Deleted', 'Deleted')], default='Pending', max_length=20),
        ),
    ]
